# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 844a2b01053890e246608d19eb53a7aa6eb76c26ba26b5c48fd5a3fadb18e8d6fe1b0defb5b2a7045361381c1f758b9807fcb638ca181f7dd30780ab7761746c

test:
  secret_key_base: 76b66cde48f0e53d0fb8af58b6d1db0ce0a77cbf1c91421fdf20caea777b6a67c78bb898e78f40ebd6ee9eb23aa7dc30eb7eb43758a9a9106a35908476adbe01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
